### ISSUE TITLE
Connection refused

### ISSUE THREAD

**Issue by xuanjiang1985** [markhilton/docker-php-fpm#3]
nginx failed (111: Connection refused) while connecting to upstream, when it was running in k8s.
here is php-svc
```
apiVersion: v1
kind: Service
metadata:
  name: php-svc
spec:
  selector:
    name: php
  ports:
  - port: 9000
    name: http-php
    targetPort: 9000
    protocol: TCP
 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-php-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      name: php
  template:
    metadata:
      labels:
        name: php
    spec:
      containers:
      - name: php
        image: crunchgeek/php-fpm:7.2
        env:
        - name: PHP_CRONTABS_PATH
          value: /app/cronttab_scripts
        ports:
        - name: http-php
          containerPort: 9000
        volumeMounts:
        - name: php-code
          mountPath: /var/www/html/
        - name: php-app
          mountPath: /app
      volumes:
      - name: php-code
        nfs:
          path: /home/data
          server: 192.168.83.143
      - name: php-app
        nfs:
          path: /home/data/phpCron
          server: 192.168.83.143
```
and crontab was invalid, this file /app/cronttab_scripts content below
```
* * * * * /usr/local/bin/php /var/www/html/lumen57/artisan schedule:run >> /dev/null 2>&1 &
```
