### ISSUE TITLE
PHP container not refreshing script updates in Docker for Windows (WSL2/NTFS regression)

### ISSUE THREAD

**Issue by bmcminn** [markhilton/docker-php-fpm#6]
This is my second attempt at setting up a Docker environment for myself so I'm still figuring things out.

Took some inspiration from your https://github.com/markhilton/docker-nginx-php-fpm-example repo, however I needed to setup MySQL and while debugging my connection errors, I noticed that PHP isn't updating edits I'm making until the service is physically restarted, which is tedious and defeats the purpose of this exercise.

My assumption is this issue exists solely in the `php-fpm` container I setup, since restarting the service refreshes the file system and my changes show up, but since I'm using volumes to map my working directory to the container I would expect my changes to show up instantly. I'm not sure if I have a fundamental misunderstanding with how this all works.

Doing some research on this behavior, `opcache.revalidate_freq` in the `php.ini` settings seemed like a promising resolution, but overwriting this value from the default `10` seconds to `1` in my `.docker/local.ini` filedoes not appear to resolve the issue.

```ini
# .docker/local.ini
[opcache]
opcache.revalidate_freq=1
```

```yaml
# docker-compose.yml
version: '3'

services:
    mysql:
        container_name: mysql
        image: mysql:5.7
        restart: unless-stopped
        tty: true
        networks:
            - backend
        ports:
            - ${DB_PORT}:3306
        volumes:
            - data:/var/lib/mysql
            - ./.docker/my.cnf:/etc/mysql/my.cnf
        environment:
            MYSQL_DATABASE: ${DB_NAME}
            MYSQL_PASSORD: ${DB_PASS}
            MYSQL_USER: ${DB_USER}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql

    nginx:
        container_name: nginx
        image: crunchgeek/nginx-pagespeed:1.17.3-r1
        working_dir: /app
        hostname: nginx
        tty: true
        ports:
            - "80:80"
            - "8080:8080"
        networks:
            - backend
        volumes:
            - .:/app
            - ./.docker:/config
        env_file: .env

    php-fpm:
        image: crunchgeek/php-fpm:7.3
        working_dir: /app/public
        hostname: php-fpm
        tty: true
        depends_on:
            - mysql
        container_name: php-fpm
        networks:
            - backend
        volumes:
            - .:/app
            - ./.docker:/config
        env_file: .env

networks:
    backend:
        driver: bridge

volumes:
    data:
        driver: local
```
